import React from 'react'
import ReactDOM from 'react-dom/client'
import TestnetFirstApp from './TestnetFirstApp'
import AppErrorBoundary from './AppErrorBoundary'
import WebAccessGate from './WebAccessGate'
import AuthGate from './AuthGate'
import CopyProtection from './CopyProtection'
import BackToTop from './BackToTop'
import { installAuthorizedFetch } from './api'
import './frontend/src/binance-demo.css'
import './master-trade-live.css'
import './terminal-theme.css'
import './subscription.css'
import './coin-analysis.css'
import './scanner-modern.css'
import './theme.css'
import './mobile-premium.css'
import './back-to-top.css'

installAuthorizedFetch()
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><CopyProtection/><BackToTop/><AppErrorBoundary><WebAccessGate><AuthGate><TestnetFirstApp/></AuthGate></WebAccessGate></AppErrorBoundary></React.StrictMode>)
