export const analystCopy = {
  ariaLabel: 'ProTreBot Analiz ve Piyasa Zekasi',
  eyebrow: 'PROTREBOT ANALİST',
  title: 'Piyasa zekası',
  description: 'Teknik sinyalleri, piyasa yapısını ve riski tek bir görünümde inceleyin.',
  selectedCoin: 'SEÇİLİ COİN',
  waiting: 'VERİ BEKLENİYOR',
  groups: {
    quick: 'HIZLI ANALİZ',
    technical: 'TEKNİK',
    decision: 'KARAR DESTEĞİ',
  },
  marketOverview: 'Piyasa özeti',
  bestLong: 'En iyi LONG',
  bestShort: 'En iyi SHORT',
  whyCoin: 'Bu coin neden?',
  selector: 'COİN SEÇİCİ',
  analysisResult: 'ANALİZ SONUCU',
  waitingResult: 'BEKLENİYOR',
  whyResult: 'BU SONUÇ NEDENİ',
  ask: 'ANALİSTE SOR',
  askHint: 'Seçili coin hakkında bir soru seçin.',
  searchCoin: 'Coin ara...',
  all: 'TÜMÜ',
  watch: 'BEKLE',
  noMatch: 'Bu aramayla eşleşen coin yok.',
  scannerWaiting: 'Tarama verisi bekleniyor',
  confidence: 'güven',
  labels: {
    'Trend Analysis': 'Trend analizi',
    Momentum: 'Momentum',
    'Volume Intelligence': 'Hacim analizi',
    'EMA Structure': 'EMA yapısı',
    'RSI / MACD': 'RSI / MACD',
    'Support / Resistance': 'Destek / direnç',
    Volatility: 'Oynaklık',
    'Market Regime': 'Piyasa rejimi',
    'Entry Analysis': 'Giriş analizi',
    'Exit Analysis': 'Çıkış analizi',
    'Risk / R:R': 'Risk / R:R',
    'Signal Confidence': 'Sinyal güveni',
  } as Record<string, string>,
} as const

export const marketCopy = {
  scanner: 'PİYASA TARAMA · GERÇEK ZAMANLI PİYASA ZEKASI',
  subtitle: 'Piyasadaki teknik fırsatları keşfedin.',
  runScan: 'TARAMAYI ÇALIŞTIR',
  scanning: 'TARANIYOR...',
  live: 'CANLI',
  paused: 'DURAKLATILDI',
  assets: 'VARLIK',
  lastScan: 'SON TARAMA',
  overview: 'PİYASA ÖZETİ',
  longSetups: 'LONG KURULUMLARI',
  shortSetups: 'SHORT KURULUMLARI',
  anomalies: 'ANOMALİLER',
  heatmap: 'PİYASA ISI HARİTASI',
  noAnomalies: 'Anomali tespit edilmedi.',
  details: 'DETAYLARI GÖR',
} as const
