export const assistantCopy = {
  tr: {
    open: 'Kais AI', close: 'Kais AI sohbetini kapat', title: 'Kais AI',
    status: {ready: 'Hazır', thinking: 'Düşünüyor', unavailable: 'Kullanılamıyor', private: 'Gizlilik modu'},
    welcome: 'Merhaba, ben Kais AI.', you: 'Sen',
    eyeStates: {idle: 'Kais AI: hazır', thinking: 'Kais AI: düşünüyor', private: 'Kais AI: gizlilik modu', error: 'Kais AI: hata', off: 'Kais AI: kapalı'},
    eyePrivacy: 'Göz simgesi dekoratiftir; sayfa içeriğini okumaz veya veri göndermez.',
    subtitle: 'Platform rehberin · işlem yapmaz', clear: 'Kais AI sohbetini temizle',
    proactiveSetting: 'Durum yoklamaları', proactiveLabel: 'Durum özeti',
    proactiveUnread: 'Okunmamış durum özeti', proactiveSaving: 'Ayar kaydediliyor...',
    proactiveHint: 'Kapattığında yeni yoklama gelmez. Ayarın hesabında saklanır.',
    proactiveError: 'Yoklama bilgisi veya ayarı alınamadı/kaydedilemedi; değişiklik doğrulanmadı.',
    empty: 'Plan, kredi, API bağlantısı ve platform kullanımı hakkında yardımcı olan bir yapay zeka asistanıyım. İşlem yapmam.',
    input: 'Kais AI mesajın', placeholder: 'Kais AI', send: 'Kais AI mesajını gönder',
    typing: 'Düşünüyor...', secret: "API Secret'ı buraya yazma.",
    secretBlocked: "Secret veya kimlik bilgilerini sohbete yazma. Paylaştıysan değiştirmeni öneririm.",
    loading: 'Mesaj hakkı yükleniyor...', retry: 'Tekrar dene', login: 'Giriş yap',
    usage: (remaining: number, total: number) => `Günlük mesaj hakkı: ${remaining}/${total}`,
    cost: (cost: number) => `${cost} kredi harcanacak`,
    confirm: 'Onayla', cancel: 'Vazgeç', confirmed: 'Onaylandı', cancelled: 'Vazgeçildi',
    renewed: 'Onay için analizi tekrar iste.',
    storage: 'Sohbet geçmişi okunurken veya kaydedilirken sorun oluştu. Kayıt yapılamazsa geçmiş yalnız bu sayfanın belleğinde kalır.',
    network: 'Ağ bağlantısı kurulamadı. Bağlantını kontrol edip tekrar deneyebilirsin.',
    uncertain: 'Onay sonucu alınamadı. Tekrar Onayla aynı onayı kullanır; çift kredi düşümü yapılmaz.',
    session: 'Oturumun sona ermiş. Devam etmek için yeniden giriş yap.',
    limit: 'Mesaj limitine ulaştın. Bekleme süresinden sonra tekrar deneyebilirsin.',
    budget: 'Asistan şu an yoğun; bütçe nedeniyle yeni yanıt üretilemiyor. Biraz sonra tekrar dene.',
    unavailable: 'Asistan şu an kullanılamıyor. Biraz sonra tekrar dene.',
    invalid: 'Sunucudan geçerli bir asistan yanıtı alınamadı.',
    forbidden: 'Bu onay artık geçerli değil veya yetkin değişti. Analizi yeniden iste.',
    credits: 'Analiz isteği şu an kabul edilmiyor. Analyst ekranından kredi bakiyesi ve limit durumunu kontrol et.',
    tooLong: (max: number) => `Mesaj en fazla ${max} karakter olabilir.`,
    wait: (seconds: number) => `Yeniden deneme: ${seconds} saniye sonra.`,
    unknown: 'Doğrulanamadı', stale: 'Veri bayat veya güncelliği doğrulanamadı.',
    age: (seconds: number) => `Veri ${seconds} saniye önce alındı.`,
    ageUnknown: 'Veri yaşı doğrulanamadı.',
    levels: 'Entry/SL/TP seviyeleri için Master Trade ekranını kullan; asistan bu seviyeleri paylaşmaz.',
    risk: 'Final Decision emir izni değildir; Confidence kazanma olasılığı değildir. Karar sana aittir. Kâr garantisi yoktur, sermaye kaybı olabilir.',
    questions: ['Premium ne kadar?', 'Kredim ne kadar?', 'API anahtarımı nereye girerim?', 'BTC için analiz durumu ne?', 'Stop loss çalışıyor mu?'],
  },
  en: {
    open: 'Kais AI', close: 'Close Kais AI chat', title: 'Kais AI',
    status: {ready: 'Ready', thinking: 'Thinking', unavailable: 'Unavailable', private: 'Private mode'},
    welcome: 'Hi, I am Kais AI.', you: 'You',
    eyeStates: {idle: 'Kais AI: ready', thinking: 'Kais AI: thinking', private: 'Kais AI: private mode', error: 'Kais AI: error', off: 'Kais AI: off'},
    eyePrivacy: 'The eye is decorative; it does not read page content or send data.',
    subtitle: 'Your platform guide · cannot trade', clear: 'Clear Kais AI chat',
    proactiveSetting: 'Status check-ins', proactiveLabel: 'Status summary',
    proactiveUnread: 'Unread status summary', proactiveSaving: 'Saving preference...',
    proactiveHint: 'Turning this off stops new check-ins. Your preference is saved to your account.',
    proactiveError: 'Could not load or save check-in information; the change has not been verified.',
    empty: 'I am an AI assistant helping with plans, credits, API connections and platform usage. I do not trade.',
    input: 'Your Kais AI message', placeholder: 'Kais AI', send: 'Send Kais AI message',
    typing: 'Thinking...', secret: 'Do not enter an API Secret here.',
    secretBlocked: 'Do not share secrets or credentials in chat. Rotate them if exposed.',
    loading: 'Loading message allowance...', retry: 'Try again', login: 'Sign in',
    usage: (remaining: number, total: number) => `Daily messages remaining: ${remaining}/${total}`,
    cost: (cost: number) => `${cost} credits will be spent`,
    confirm: 'Confirm', cancel: 'Cancel', confirmed: 'Confirmed', cancelled: 'Cancelled',
    renewed: 'Request the analysis again to obtain confirmation.',
    storage: 'There was a problem reading or saving chat history. If storage is unavailable, history remains only in this page’s memory.',
    network: 'Could not connect. Check your network and try again.',
    uncertain: 'The confirmation result is unknown. Confirm again reuses the same approval without a duplicate charge.',
    session: 'Your session has expired. Sign in again to continue.',
    limit: 'You reached the message limit. Try again after the waiting period.',
    budget: 'The assistant is busy; the budget prevents new responses. Please try again later.',
    unavailable: 'The assistant is unavailable right now. Please try again later.',
    invalid: 'The server did not return a valid assistant response.',
    forbidden: 'This confirmation is no longer valid or your access changed. Request the analysis again.',
    credits: 'The analysis request cannot be accepted right now. Check your credit balance and limits in Analyst.',
    tooLong: (max: number) => `Your message can contain at most ${max} characters.`,
    wait: (seconds: number) => `Try again in ${seconds} seconds.`,
    unknown: 'Could not verify', stale: 'Data is stale or its freshness could not be verified.',
    age: (seconds: number) => `Data was fetched ${seconds} seconds ago.`,
    ageUnknown: 'Data age could not be verified.',
    levels: 'For Entry/SL/TP levels, use Master Trade; the assistant does not share these levels.',
    risk: 'Final Decision is not order permission; Confidence is not a winning probability. The decision is yours. Profit is not guaranteed and capital can be lost.',
    questions: ['How much is Premium?', 'How many credits do I have?', 'Where do I enter my API key?', 'What is the analysis status for BTC?', 'Is my stop loss working?'],
  },
} as const

export const analystCopy = {
  ariaLabel: 'KaiStrade Analiz ve Piyasa Zekasi',
  eyebrow: 'ANALİST',
  title: 'Piyasa zekası',
  description: 'Teknik sinyalleri, piyasa yapısını ve riski tek bir görünümde inceleyin.',
  analysisCost: (cost: number) => `Taze analiz: ${cost} kredi. Önbellek ücretsiz.`,
  selectedCoin: 'SEÇİLİ COİN',
  waiting: 'VERİ BEKLENİYOR',
  groups: {
    quick: 'HIZLI ANALİZ',
    technical: 'TEKNİK',
    decision: 'KARAR DESTEĞİ',
  },
  marketOverview: 'Piyasa özeti',
  bestLong: 'En iyi LONG',
  bestShort: 'En iyi SHORT',
  whyCoin: 'Bu coin neden?',
  selector: 'COİN SEÇİCİ',
  analysisResult: 'ANALİZ SONUCU',
  waitingResult: 'BEKLENİYOR',
  whyResult: 'BU SONUÇ NEDENİ',
  ask: 'ANALİSTE SOR',
  askHint: 'Seçili coin hakkında bir soru seçin.',
  searchCoin: 'Coin ara...',
  all: 'TÜMÜ',
  watch: 'BEKLE',
  noMatch: 'Bu aramayla eşleşen coin yok.',
  scannerWaiting: 'Tarama verisi bekleniyor',
  confidence: 'güven',
  resultEmpty: 'Bir analiz seçin, sonuç burada görünecek.',
  resultTitle: 'Detaylı Analiz Sonucu',
  loading: 'Analiz hazırlanıyor...',
  retry: 'Tekrar dene',
  selectCoin: 'Önce bir coin seçin.',
  dataUnavailableHint: 'Tarama verisini yenileyip tekrar deneyin.',
  marketTrend: 'Genel eğilim',
  rising: 'Yükseliş ağırlıklı',
  falling: 'Düşüş ağırlıklı',
  balanced: 'Dengeli görünüm',
  opportunities: 'Fırsatlar',
  declining: 'Düşenler',
  score: 'Skor',
  price: 'Fiyat',
  riskReward: 'R/R',
  detail: 'Detay',
  noLong: 'Şu an LONG sinyali yok.',
  noShort: 'Şu an SHORT sinyali yok.',
  dataUnavailable: 'Güncel piyasa verisi alınamadı.',
  trend: 'Trend',
  momentum: 'Momentum',
  volume: 'Hacim',
  ema: 'EMA yapısı',
  oscillator: 'RSI / MACD',
  supportResistance: 'Destek / direnç',
  volatility: 'Oynaklık',
  regime: 'Piyasa rejimi',
  entry: 'Giriş',
  exit: 'Çıkış',
  risk: 'Risk / R:R',
  signalConfidence: 'Sinyal güveni',
  mtfAlignment: 'MTF uyumu',
  signalReason: 'Sinyal gerekçesi',
  technical: 'Teknik görünüm',
  decision: 'Karar görünümü',
  highest: 'En çok yükselen 3',
  lowest: 'En çok düşen 3',
  labels: {
    'Trend Analysis': 'Trend analizi',
    Momentum: 'Momentum',
    'Volume Intelligence': 'Hacim analizi',
    'EMA Structure': 'EMA yapısı',
    'RSI / MACD': 'RSI / MACD',
    'Support / Resistance': 'Destek / direnç',
    Volatility: 'Oynaklık',
    'Market Regime': 'Piyasa rejimi',
    'Entry Analysis': 'Giriş analizi',
    'Exit Analysis': 'Çıkış analizi',
    'Risk / R:R': 'Risk / R:R',
    'Signal Confidence': 'Sinyal güveni',
  } as Record<string, string>,
} as const

export const marketCopy = {
  scanner: 'PİYASA TARAMA · GERÇEK ZAMANLI PİYASA ZEKASI',
  subtitle: 'Piyasadaki teknik fırsatları keşfedin.',
  runScan: 'TARAMAYI ÇALIŞTIR',
  scanning: 'TARANIYOR...',
  live: 'CANLI',
  paused: 'DURAKLATILDI',
  assets: 'VARLIK',
  lastScan: 'SON TARAMA',
  overview: 'PİYASA ÖZETİ',
  longSetups: 'LONG KURULUMLARI',
  shortSetups: 'SHORT KURULUMLARI',
  anomalies: 'ANOMALİLER',
  heatmap: 'PİYASA ISI HARİTASI',
  noAnomalies: 'Anomali tespit edilmedi.',
  details: 'DETAYLARI GÖR',
} as const

export const liveCopy = {
  ariaLabel: 'Gerçek Futures Hazırlık Merkezi',
  eyebrow: 'GERÇEK FUTURES HAZIRLIK MERKEZİ',
  title: 'Live Trading',
  description: 'Salt-okunur hesap durumu ve güvenli dry-run hazırlığı.',
  unknown: 'UNKNOWN', ready: 'READY', blocked: 'BLOCKED', disconnected: 'DISCONNECTED',
  status: { liveTrading: 'Live Trading', autoTrade: 'Auto Trade', marketData: 'Market Data', liveAccount: 'Live Account', risk: 'Risk', exposure: 'Exposure', protection: 'Protection', recovery: 'Recovery', emergency: 'Emergency' },
  now: 'ŞİMDİ NE YAPMALI', configureCredentials: 'CANLI CREDENTIAL YAPILANDIR', refreshStatus: 'DURUMU YENİLE',
  credentialsTitle: 'Canlı credential yapılandırması', credentialsHint: 'Anahtarlar yalnızca mevcut şifreli backend kasasına gönderilir.',
  apiKey: 'API KEY', secretKey: 'SECRET KEY', saveAndConnect: 'KAYDET VE SALT-OKUNUR BAĞLAN', testConnection: 'BAĞLANTIYI TEST ET', close: 'KAPAT',
  manualOrder: 'MANUEL EMİR', orderSummary: 'EMİR ÖZETİ', symbol: 'Sembol', side: 'Yön', long: 'LONG', short: 'SHORT', orderType: 'Emir türü', market: 'MARKET', limit: 'LIMIT', limitPrice: 'Limit fiyatı', margin: 'Miktar / Marjin', leverage: 'Kaldıraç', stopLoss: 'Stop Loss', tp1: 'TP1', tp2: 'TP2', tp3: 'TP3',
  fillAnalysis: 'ANALİZDEN DOLDUR', reviewOrder: 'EMRİ DRY-RUN İNCELE', lastOrder: 'SON EMİR', protectionSummary: 'KORUMA ÖZETİ', recovery: 'RECOVERY', checkRecovery: 'RECOVERY KONTROLÜ', emergencyStop: 'ACİL DURDUR', history: 'PLAN-DIŞI BINANCE GEÇMİŞİ', noRecord: 'Kayıt yok', noSelectedCoin: 'Seçili coin yok; önce Analyst/Coin Analiz sayfasından bir coin seçin.', noHistory: 'Plan-dışı Binance kaydı yok.', connectionLost: 'Bağlantı yok',
} as const
